# primary purposes Human readable 

# 1. Defines the default mode of enforcement(strict,warn,off)
# 2. Enables/control plugins
# 3. sets logging,debuging, test-gen options
# 4. Allows per-project consistency for teams or CI

mode: strict # defualt strict|warn|off

plugins:
  # list of plugins to enable
  enabled: true
  paths:
    - plugins/slack_notifier.py
    - plugins/test_collector.py
    - plugins/violation_counter.py

test_generation:
   export_test_stub: false
   export_stub_path: tests/generated
   include_docstring: true
